spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydatabase}
    username: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:mypassword}
    driver-class-name: org.postgresql.Driver

  flyway:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mydatabase}
    user: ${SPRING_DATASOURCE_USERNAME:myuser}
    password: ${SPRING_DATASOURCE_PASSWORD:mypassword}
    enabled: true
    validateMigrationNaming: true
    schemas: my_schema,public
    baselineOnMigrate: true
#    locations: classpath:db/migration
#    cleanDisabled: false


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  logging:level:org:hibernate: TRACE
  logging:level:org:hibernate:SQL: DEBUG
  logging:level:org:hibernate:type:descriptor:sql: TRACE
  logging:
    level:
      org:
        flywaydb=DEBUG:

